version: "3.7"


services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      REACT_APP_API_ENDPOINT: http://localhost:8000/

volumes:
  db-data:
