version: "3.7"


services:
  postgres:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      - ./api/scripts/wait-for-postgres.sh:/home/wait-for-postgres.sh
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{cookiecutter.name}}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: {{cookiecutter.name}}
        POSTGRES_PORT: 5432
        ALLOWED_HOSTS: '["*"]'

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      REACT_APP_API_ENDPOINT: http://localhost:8000/api
      REACT_APP_IS_DEVELOPMENT: "true"


volumes:
  db-data:
